name: test_task
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  cached_network_image: ^3.3.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_staggered_grid_view: ^0.7.0
  get: ^4.6.6
  provider: ^6.1.1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: playfair
      fonts:
        - asset: assets/fonts/PlayfairDisplay-Regular.ttf
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
flutter_assets:
  assets_path: assets/
  output_path: lib/imagePaths/
  filename: assets.dart
  field_prefix: null
